version = 0.1

[default.deploy.parameters]
stack_name = "test-app"
resolve_s3 = true
s3_prefix = "test-app"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "DBHost=\"database-1.cfusuocsw7ay.eu-west-2.rds.amazonaws.com\" DBPort=\"5432\" DBName=\"postgres\" DBUser=\"postgres\" DBPassword=\"sagViz-qajha1-mehcek\""

[default.global.parameters]
region = "eu-west-2"
